run:
  timeout: 5m

linters:
  enable:
    # Required by assessment
    - gocyclo
    - revive
    # Standard linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  gocyclo:
    # Assessment requirement: no function may exceed complexity of 10
    min-complexity: 10
  revive:
    severity: warning
    rules:
      - name: exported
      - name: var-naming
      - name: error-return
      - name: error-strings
      - name: unexported-return

issues:
  # Fail on any warning
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Ignore errcheck in tests - test handlers don't need error checking
    - path: _test\.go
      linters:
        - errcheck
